# Generated by Django 5.0.6 on 2024-07-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
