# Generated by Django 5.0.6 on 2024-08-02 16:15

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='main/static/images/default.jpg', null=True, upload_to=users.utils.user_directory_path),
        ),
    ]
