# Generated by Django 5.0.6 on 2024-08-02 16:17

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', null=True, upload_to=users.utils.user_directory_path),
        ),
    ]
